import Link from "next/link";
import { JsonLd } from "@/components/JsonLd";
import { Questions } from "@/components/marketing/MarketingPage";
import { RecruitingLink } from "@/components/marketing/RecruitingLink";
import { actionClass } from "@/components/ui/actions";
import { CREDIT_PRICES } from "@/lib/ai/credit-policy";
import { PUBLIC_PRICING_PLANS, TRIAL_CREDITS, TRIAL_DAYS } from "@/lib/billing/plans";
import { BUSINESS_ONLY_NOTICE } from "@/lib/legal/policy";
import { MARKETING_PAGE, pageMetadata } from "@/lib/seo";
import { breadcrumbStructuredData } from "@/lib/structured-data";
import { PricingContext } from "./PricingContext";
import styles from "./pricing.module.css";
export const metadata = pageMetadata(MARKETING_PAGE.pricing);
const audiences = { basic: "Für einzelne Kundenmandate.", pro: "Für regelmäßig arbeitende Recruiter.", business: "Für mehrere parallele Mandate im Team." };
const questions = [
  { question: "Was passiert nach den 14 Tagen?", answer: <p>Nach dem tatsächlichen Stripe-Trial-Ende beginnt automatisch Ihr gewählter Monatstarif, sofern Sie nicht rechtzeitig kündigen. Das erste Abrechnungsdatum sehen Sie nach Aktivierung in Ihrem Konto. Stripe erstellt die Rechnung und versucht die Zahlung. Ein Zahlungsversuch garantiert keine erfolgreiche Abbuchung.</p> },
  { question: "Wie kündige ich den Trial?", answer: <p>Selbstständig im <Link href="/konto">Kontobereich</Link>, ohne Supportkontakt. Bei bestätigter Kündigung vor Trial-Ende erfolgt keine erste kostenpflichtige Verlängerung. Die verbleibenden Trial-Credits bleiben bis zum bestätigten Enddatum nutzbar. Nach einer bezahlten Periode kündigen Sie zum Ende der laufenden Monatsperiode.</p> },
  { question: "Was passiert bei aufgebrauchten Trial-Credits?", answer: <p>Das einmalige Trial-Kontingent wird nicht nachgefüllt. Verbrauchte Credits lösen keine vorzeitige Abbuchung aus. Ein erneuter Checkout, Kontowechsel oder Tarifwechsel startet keinen neuen Trial. Gespeicherte Projektinformationen bleiben lesbar.</p> },
  { question: "Was kostet eine Freelancer-Beauftragung?", answer: <p>XPORTAL berechnet für neue Vorgänge keine Vermittlungsprovision, Erfolgsgebühr oder zusätzliche Beauftragungsgebühr. Der Tarif bezahlt die Software-Nutzung. Freelancer-Honorar und Vertrag vereinbaren Sie direkt mit dem Freelancer. Historische Verträge bleiben unverändert.</p> },
  { question: "Was geschieht bei einem Zahlungsfehler?", answer: <p>Sie erhalten einen Hinweis und können Ihr Zahlungsmittel in der Abrechnung aktualisieren. Ohne bestätigte Zahlung entstehen keine neuen Monatscredits. Nach Ende Ihrer vorhandenen Berechtigung sind neue kostenpflichtige KI-Läufe gesperrt; Projekte, Rechnungen und Kontoverwaltung bleiben erreichbar.</p> },
  { question: "Was gilt für bestehende Guthaben?", answer: <p>Legitim zugesagtes Bestandsguthaben bleibt erhalten. Neue Gäste und neue Registrierungen erhalten kein zusätzliches Bonusguthaben. Die einmaligen {TRIAL_CREDITS} Trial-Credits werden erst nach serverseitig verifizierter Kartenhinterlegung freigeschaltet.</p> },
];
export default function PricingPage() {
  const plans = PUBLIC_PRICING_PLANS.filter((plan) => plan.billingModel === "fixed_monthly");
  return <main id="main-content" className={styles.main} tabIndex={-1}>
    <JsonLd data={breadcrumbStructuredData(MARKETING_PAGE.pricing)} /><PricingContext />
    <header className={styles.hero}><div><p className={styles.eyebrow}>Recruiting-Software im Monatsabonnement</p><h1>{TRIAL_DAYS} Tage testen.<br /><span>Danach Ihr gewählter Tarif.</span></h1><p className={styles.lead}>Projektanforderungen strukturieren, Profile nachvollziehbar abgleichen und mehrere Mandate speichern. Neue Kontakte und Beauftragungen sind provisionsfrei.</p><div className={styles.heroActions}><a href="#tarife" className={actionClass("primary")}>Tarif für den Trial wählen</a><RecruitingLink href="/freelancer-finden#ergebnisbeispiel" event="demo_viewed" className={actionClass("secondary")}>Beispiel ohne Karte ansehen</RecruitingLink></div></div><aside className={styles.creditThesis} aria-label="Trial-Konditionen"><p>Einmaliges Trial-Kontingent</p><strong>{TRIAL_CREDITS}</strong><span>Credits insgesamt für {TRIAL_DAYS} Tage</span><ul><li>Karte bei Stripe erforderlich</li><li>Automatische monatliche Verlängerung danach</li><li>Vor Trial-Ende selbstständig kündbar</li><li>Keine vorzeitige Abbuchung bei Verbrauch</li></ul></aside></header>
    <section className={styles.planSection} id="tarife" aria-label="Monatstarife"><div className={`${styles.cards} ${styles.trialCards}`}>{plans.map((plan) => <article key={plan.id} className={`${styles.card} ${plan.recommended ? styles.recommended : ""}`}><div className={styles.cardTopline}><p className={styles.planName}>{plan.label}</p></div><p className={styles.audience}>{audiences[plan.id as keyof typeof audiences]}</p><div className={styles.usageExample}><strong>{TRIAL_DAYS} Tage kostenlos</strong><span>{TRIAL_CREDITS} Credits insgesamt · Karte erforderlich</span></div><div className={styles.priceBlock}><p className={styles.price}>{plan.euro} €</p><span>netto / Monat nach dem Trial, zzgl. USt.</span></div><p className={styles.creditVolume}><strong>{plan.monthlyCredits.toLocaleString("de-DE")}</strong> Credits je bezahlter Monatsperiode</p><ul className={styles.features}><li>Projektanalysen und Profilabgleich</li><li>Zusätzliche Recherche bewusst starten</li><li>Mandate und Auswahl speichern</li><li>Freigegebene Kontakt- und Dokumentwege</li><li>Keine Vermittlungsprovision für neue Vorgänge</li></ul><RecruitingLink href={`/chat?checkout=${plan.id}`} event="trial_cta_clicked" plan={plan.id} className={actionClass("primary", { block: true, className: styles.cardAction })}>14 Tage kostenlos testen</RecruitingLink><p className={styles.checkoutNote}>Danach automatisch {plan.euro} € netto monatlich, zzgl. USt. Monatlich zum Periodenende kündbar. Karte hinterlegen und Angebot erst bei Stripe bestätigen.</p></article>)}</div><p className={styles.checkoutNote}>Der Trial beginnt nach bestätigter E-Mail und serverseitig verifiziertem Stripe-Abschluss. Das Konto zeigt den tatsächlichen Stripe-Zeitpunkt. Ein Checkout-Erfolgslink allein schaltet keine Rechte frei. {BUSINESS_ONLY_NOTICE}</p></section>
    <section className={styles.actionSection} aria-labelledby="actions-title"><div className={styles.sectionIntro}><div><p className={styles.eyebrow}>Kontingent verstehen</p><h2 id="actions-title">Was verbraucht Credits?</h2></div><p>Die Anwendung nennt den Verbrauch vor einer Aktion. Fehlgeschlagene KI-Läufe werden nicht belastet. Abgeschlossene Recherche ohne passende Treffer bleibt ein verbrauchter Lauf.</p></div><div className={styles.actionGrid}>{Object.values(CREDIT_PRICES).map((price) => <article key={price.label}><p>{price.label}</p><strong>{price.credits} Credits</strong></article>)}</div></section>
    <section className={styles.faq}><div><p className={styles.eyebrow}>Abrechnung und Zugang</p><h2>Vor dem Start klar.</h2></div><Questions items={questions} /></section>
    <section className={styles.finalCta}><div><h2>Am nächsten Mandat ausprobieren.</h2><p>{TRIAL_DAYS} Tage · {TRIAL_CREDITS} Credits insgesamt · Karte erforderlich · anschließend gewählter Monatstarif.</p></div><a href="#tarife" className={actionClass("primary")}>Tarif wählen</a></section>
  </main>;
}
