-- Legacy synthetic acceptance fixtures. They are inserted only to keep older
-- database checks reproducible and are removed again in this same seed file.
-- A completed reset must contain no demo freelancer profile.

insert into public.freelancer_profiles (
  id,
  slug,
  display_name,
  role_title,
  skill_tags,
  languages,
  location_text,
  work_modes,
  experience_summary,
  verified_facts,
  self_reported_facts,
  references_summary,
  verification_status,
  hourly_rate_minor,
  day_rate_minor,
  currency,
  profile_status,
  availability_status,
  availability_from,
  availability_updated_at,
  intro_policy,
  booking_url,
  demo_status
) values
  (
    '10000000-0000-4000-8000-000000000001',
    'helena-vogt-demo',
    'Helena Vogt',
    'Senior React Engineer',
    array['react', 'typescript', 'next.js', 'frontend architecture', 'testing'],
    array['de', 'en'],
    'Berlin, Germany',
    array['remote', 'hybrid'],
    'Synthetic profile for testing a senior frontend shortlist. The record demonstrates a React and TypeScript delivery profile without representing a real person.',
    array[
      'Demo: Synthetic record; no real person is represented',
      'Location: Berlin, Germany'
    ],
    array[
      'Skill: react',
      'Skill: typescript',
      'Skill: next.js',
      'Skill: frontend architecture',
      'Skill: testing',
      'Language: German',
      'Language: English',
      'Experience: 8+ years frontend delivery',
      'Experience: Design-system and accessibility experience'
    ],
    'Synthetic references for UI testing only; no real references were contacted.',
    'identity_checked',
    9500,
    72000,
    'EUR',
    'active',
    'available',
    current_date + 14,
    now(),
    'free',
    'https://example.com/demo-booking/helena-vogt',
    'demo'
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    'amir-rahman-demo',
    'Amir Rahman',
    'Full-stack TypeScript Engineer',
    array['typescript', 'node.js', 'react', 'postgresql', 'api integration'],
    array['en', 'de'],
    'Hamburg, Germany',
    array['remote'],
    'Synthetic full-stack profile used to test commercial constraints, remote delivery and a manual-approval introduction.',
    array[
      'Demo: Synthetic record; no real person is represented',
      'Location: Hamburg, Germany'
    ],
    array[
      'Skill: typescript',
      'Skill: node.js',
      'Skill: react',
      'Skill: postgresql',
      'Skill: api integration',
      'Language: English',
      'Language: German',
      'Experience: 6+ years product engineering',
      'Experience: Remote-first collaboration'
    ],
    'Synthetic references for UI testing only; no real references were contacted.',
    'references_checked',
    11000,
    85000,
    'EUR',
    'active',
    'available',
    current_date + 7,
    now(),
    'manual_approval',
    null,
    'demo'
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    'sofia-marin-demo',
    'Sofia Marin',
    'Requirements & Business Analyst',
    array['requirements management', 'business analysis', 'bpmn', 'stakeholder workshops', 'acceptance criteria'],
    array['de', 'en', 'es'],
    'Cologne, Germany',
    array['remote', 'on_site', 'hybrid'],
    'Synthetic analyst profile for testing German-language requirements discovery, BPMN workshops and traceable acceptance criteria.',
    array['Demo: Synthetic record; no real person is represented'],
    array[
      'Skill: requirements management',
      'Skill: business analysis',
      'Skill: bpmn',
      'Skill: stakeholder workshops',
      'Skill: acceptance criteria',
      'Language: German',
      'Language: English',
      'Language: Spanish',
      'Location: Cologne, Germany',
      'Experience: Requirements facilitation for SME projects',
      'Experience: BPMN 2.0 workshop experience'
    ],
    'No real references exist because this is a synthetic acceptance-test profile.',
    'unverified',
    9800,
    78000,
    'EUR',
    'active',
    'available',
    current_date + 3,
    now(),
    'free',
    'https://example.com/demo-booking/sofia-marin',
    'demo'
  ),
  (
    '10000000-0000-4000-8000-000000000004',
    'leona-berg-demo',
    'Leona Berg',
    'Delivery & Project Manager',
    array['project management', 'process management', 'delivery management', 'clickup', 'risk management', 'vendor coordination'],
    array['de', 'en'],
    'Munich, Germany',
    array['remote', 'on_site', 'hybrid'],
    'Synthetic project-management profile for testing time-sensitive introductions and multi-party delivery coordination.',
    array[
      'Demo: Synthetic record; no real person is represented',
      'Location: Munich, Germany'
    ],
    array[
      'Skill: project management',
      'Skill: process management',
      'Skill: delivery management',
      'Skill: clickup',
      'Skill: risk management',
      'Skill: vendor coordination',
      'Language: German',
      'Language: English',
      'Experience: Cross-functional delivery leadership',
      'Experience: Vendor and milestone coordination'
    ],
    'Synthetic references for UI testing only; no real references were contacted.',
    'operator_verified',
    null,
    90000,
    'EUR',
    'active',
    'available',
    current_date + 21,
    now(),
    'manual_approval',
    null,
    'demo'
  ),
  (
    '10000000-0000-4000-8000-000000000005',
    'noah-petrov-demo',
    'Noah Petrov',
    'Data & AI Integration Engineer',
    array['python', 'postgresql', 'openai api', 'data pipelines', 'observability'],
    array['en', 'de'],
    'Prague, Czechia',
    array['remote'],
    'Synthetic data-engineering profile retained in a paused state to verify that paused profiles never enter a new shortlist.',
    array['Demo: Synthetic record; no real person is represented'],
    array[
      'Skill: python',
      'Skill: postgresql',
      'Skill: openai api',
      'Skill: data pipelines',
      'Skill: observability',
      'Language: English',
      'Language: German',
      'Location: Prague, Czechia',
      'Experience: LLM gateway integration',
      'Experience: Production observability'
    ],
    'No real references exist because this is a synthetic acceptance-test profile.',
    'unverified',
    10500,
    82000,
    'EUR',
    'paused',
    'available',
    current_date + 5,
    now(),
    'free',
    'https://example.com/demo-booking/noah-petrov',
    'demo'
  ),
  (
    '10000000-0000-4000-8000-000000000006',
    'priya-nair-demo',
    'Priya Nair',
    'Cybersecurity & Compliance Consultant',
    array['information security', 'iso 27001', 'gdpr', 'risk assessment', 'security controls'],
    array['en', 'de'],
    'Frankfurt, Germany',
    array['remote', 'hybrid'],
    'Synthetic security profile retained as unavailable to verify immediate eligibility removal and honest no-match handling.',
    array['Demo: Synthetic record; no real person is represented'],
    array[
      'Skill: information security',
      'Skill: iso 27001',
      'Skill: gdpr',
      'Skill: risk assessment',
      'Skill: security controls',
      'Language: English',
      'Language: German',
      'Location: Frankfurt, Germany',
      'Experience: ISO 27001 readiness work',
      'Experience: GDPR-aligned control mapping'
    ],
    'Synthetic references for UI testing only; no real references were contacted.',
    'unverified',
    12500,
    98000,
    'EUR',
    'unavailable',
    'unavailable',
    null,
    now(),
    'manual_approval',
    null,
    'demo'
  )
on conflict (slug) do nothing;

-- Production and freshly reset environments use only operator-curated real
-- profiles. Synthetic people and example.com booking URLs must not survive the
-- seed transaction.
delete from public.freelancer_profiles where demo_status = 'demo';

-- Provisional defaults: the controller must approve these periods before
-- production. They configure cleanup; they do not schedule destructive jobs.
insert into public.retention_policies (
  record_type,
  retention_days,
  deletion_mode,
  is_enabled,
  notes
) values
  ('anonymous_auth_users', 30, 'hard_delete', true,
   'Delete abandoned anonymous Supabase Auth users only after confirming that no active workspace or claim remains.'),
  ('guest_claims', 30, 'hard_delete', true,
   'Delete expired or consumed claim hashes. Raw claim tokens are never stored.'),
  ('messages', 180, 'hard_delete', true,
   'Delete project conversation state after the approved inactivity period or earlier on a valid user deletion request.'),
  ('projects', 365, 'operator_review', true,
   'Review inactive projects before deletion; project deletion cascades owned conversation and result records.'),
  ('shortlists_and_matches', 365, 'hard_delete', true,
   'Retain deterministic result snapshots only for the approved reconstruction and dispute window.'),
  ('intro_bookings', 730, 'operator_review', true,
   'Keep only minimal booking state and reference; never retain a full Calendly payload.'),
  ('engagements', 2555, 'operator_review', true,
   'Provisional seven-year operational record period; controller and tax/legal review required before production.'),
  ('audit_events', 730, 'anonymize', true,
   'Pseudonymize on user deletion and review final deletion period against security and legal obligations.'),
  ('ai_usage', 90, 'hard_delete', true,
   'Delete HMAC-subject usage buckets and settled reservations after cost reconciliation and reporting.'),
  ('unsettled_ai_reservations', 1, 'operator_review', true,
   'Reconcile stale reservations as timeout/cancelled before deletion; never silently release live reservations.')
on conflict (record_type) do nothing;
