import {
  type FreelancerProfile,
  FreelancerProfileSchema,
  type LabeledFact,
} from "../../lib/domain";

const verified = (value: string): LabeledFact => ({ value, source: "verified" });
const selfReported = (value: string): LabeledFact => ({
  value,
  source: "self_reported",
});

export const profileFixtures: readonly FreelancerProfile[] = [
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000001",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "active",
    displayName: "Anna Keller",
    role: "Senior React Engineer",
    skillTags: [verified("React"), verified("TypeScript"), selfReported("Next.js")],
    languages: [verified("German"), verified("English")],
    location: verified("Berlin"),
    workModes: ["remote", "on_site", "hybrid"],
    experienceSummary: {
      value: "Eight years delivering TypeScript web applications.",
      source: "verified",
    },
    qualifications: [verified("AWS Certified Developer")],
    contractualCapabilities: [verified("NDA"), verified("EU invoicing")],
    referenceStatus: "verified",
    hourlyRate: { amount: 85, currency: "EUR" },
    dayRate: { amount: 680, currency: "EUR" },
    minimumProjectBudget: { amount: 3_000, currency: "EUR" },
    availability: {
      status: "available",
      availableFrom: "2026-08-15",
      checkedAt: "2026-08-06T08:00:00.000Z",
    },
    introPolicy: {
      type: "premium",
      label: "Introduction after operator confirmation",
      bookingUrl: "https://calendly.com/example/anna",
    },
  }),
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000002",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "active",
    displayName: "Boris Neumann",
    role: "React Developer",
    skillTags: [selfReported("React"), verified("TypeScript")],
    languages: [selfReported("German"), verified("English")],
    location: selfReported("Hamburg"),
    workModes: ["remote"],
    experienceSummary: {
      value: "Frontend delivery for early-stage product teams.",
      source: "self_reported",
    },
    qualifications: [],
    contractualCapabilities: [selfReported("NDA")],
    referenceStatus: "self_reported",
    hourlyRate: { amount: 70, currency: "EUR" },
    dayRate: { amount: 560, currency: "EUR" },
    minimumProjectBudget: { amount: 2_000, currency: "EUR" },
    availability: {
      status: "available",
      availableFrom: "2026-08-10",
      checkedAt: "2026-08-06T08:05:00.000Z",
    },
    introPolicy: {
      type: "free",
      label: "Free introductory call",
      bookingUrl: "https://calendly.com/example/boris",
    },
  }),
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000003",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "active",
    displayName: "Clara Vogt",
    role: "Full-stack Engineer",
    skillTags: [verified("React"), verified("TypeScript"), verified("Next.js")],
    languages: [verified("German"), verified("English")],
    location: verified("Berlin"),
    workModes: ["remote", "hybrid"],
    experienceSummary: {
      value: "Full-stack product engineering for regulated companies.",
      source: "verified",
    },
    qualifications: [selfReported("AWS Certified Developer")],
    contractualCapabilities: [verified("NDA"), verified("EU invoicing")],
    referenceStatus: "verified",
    hourlyRate: { amount: 90, currency: "EUR" },
    dayRate: { amount: 720, currency: "EUR" },
    minimumProjectBudget: { amount: 4_000, currency: "EUR" },
    availability: {
      status: "available",
      availableFrom: "2026-08-20",
      checkedAt: "2026-08-06T08:10:00.000Z",
    },
    introPolicy: {
      type: "premium",
      label: "Introduction after operator confirmation",
      bookingUrl: "https://calendly.com/example/clara",
    },
  }),
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000004",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "paused",
    displayName: "David Stein",
    role: "Principal React Consultant",
    skillTags: [verified("React"), verified("TypeScript"), verified("Next.js")],
    languages: [verified("German"), verified("English")],
    location: verified("Berlin"),
    workModes: ["remote", "on_site", "hybrid"],
    experienceSummary: {
      value: "Principal-level frontend architecture and delivery.",
      source: "verified",
    },
    qualifications: [],
    contractualCapabilities: [verified("NDA")],
    referenceStatus: "verified",
    hourlyRate: { amount: 75, currency: "EUR" },
    dayRate: { amount: 600, currency: "EUR" },
    minimumProjectBudget: { amount: 2_500, currency: "EUR" },
    availability: {
      status: "available",
      availableFrom: "2026-08-01",
      checkedAt: "2026-08-06T08:15:00.000Z",
    },
    introPolicy: {
      type: "premium",
      label: "Introduction after operator confirmation",
      bookingUrl: null,
    },
  }),
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000005",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "active",
    displayName: "Elena Rossi",
    role: "Requirements Manager",
    skillTags: [verified("Requirements Management"), verified("Process Management")],
    languages: [verified("English"), selfReported("German")],
    location: verified("Munich"),
    workModes: ["remote", "on_site"],
    experienceSummary: {
      value: "Requirements engineering for industrial programmes.",
      source: "verified",
    },
    qualifications: [verified("IREB CPRE")],
    contractualCapabilities: [verified("NDA"), verified("EU invoicing")],
    referenceStatus: "verified",
    hourlyRate: null,
    dayRate: { amount: 800, currency: "EUR" },
    minimumProjectBudget: { amount: 5_000, currency: "EUR" },
    availability: {
      status: "available",
      availableFrom: "2026-09-01",
      checkedAt: "2026-08-06T08:20:00.000Z",
    },
    introPolicy: {
      type: "free",
      label: "Free introductory call",
      bookingUrl: "https://calendly.com/example/elena",
    },
  }),
  FreelancerProfileSchema.parse({
    id: "00000000-0000-4000-8000-000000000006",
    dataVersion: "seed-2026-08-06.1",
    demoStatus: "demo",
    profileStatus: "active",
    displayName: "Farid Hassan",
    role: "Security Engineer",
    skillTags: [verified("Information Security"), selfReported("Cybersecurity")],
    languages: [verified("German"), verified("English")],
    location: verified("Cologne"),
    workModes: ["remote", "hybrid"],
    experienceSummary: {
      value: "Security reviews and implementation support.",
      source: "self_reported",
    },
    qualifications: [verified("CISSP")],
    contractualCapabilities: [verified("NDA"), verified("EU invoicing")],
    referenceStatus: "verified",
    hourlyRate: { amount: 110, currency: "EUR" },
    dayRate: { amount: 880, currency: "EUR" },
    minimumProjectBudget: { amount: 4_500, currency: "EUR" },
    availability: {
      status: "unavailable",
      availableFrom: null,
      checkedAt: "2026-08-06T08:25:00.000Z",
    },
    introPolicy: {
      type: "premium",
      label: "Introduction after operator confirmation",
      bookingUrl: null,
    },
  }),
] as const;
