import Link from "next/link";
import "@/app/styles/legal.css";
import { PublicDocumentIntro, PublicFooter, PublicHeader } from "@/components/public/PublicChrome";
import { BUSINESS_ONLY_NOTICE, PROVIDER_ADDRESS, SAAS_TERMS_REVIEW, SAAS_TERMS_VERSION } from "@/lib/legal/policy";
import { CREDIT_PLANS, PUBLIC_PRICING_PLANS, TRIAL_CREDITS, TRIAL_DAYS } from "@/lib/billing/plans";
export const metadata = { title: "Bedingungen der Recruiting-Software | XPORTAL", description: "Bedingungen für die provisionsfreie Recruiting-Software und den 14-Tage-Trial mit Karte.", robots: { index: false, follow: true } };
export default function TermsPage() { return <div className="xlegal" lang="de"><PublicHeader context={`SaaS-Bedingungen · ${SAAS_TERMS_VERSION}`} /><main className="xlegal-document">
  <PublicDocumentIntro eyebrow="Bedingungen der Recruiting-Software" title="Sie bezahlen die Software-Nutzung." signal={{ label: "Status", value: SAAS_TERMS_REVIEW.label }}><p>Diese Fassung beschreibt das neue Software-Abonnement für regelmäßig arbeitende Recruiter und IT-Personaldienstleister. {BUSINESS_ONLY_NOTICE}</p></PublicDocumentIntro>
  <section><h2>1. Anbieter und Geltungsbereich</h2><div><p>Anbieter ist XPORTAL — 300, Roman Dering, Einzelunternehmen, {PROVIDER_ADDRESS}. Kontakt: <a href="mailto:info@x-portal.eu">info@x-portal.eu</a>.</p><p>Für historische Konten und Vorgänge bleiben die jeweils wirksam vereinbarten Bedingungen, Rechnungen und Guthaben maßgeblich. Diese Überarbeitung ändert sie nicht rückwirkend. Die frühere <Link href="/terms/historisch">AGB-Fassung 1.1</Link> und die <Link href="/vermittlungsbedingungen">historischen Vermittlungsbedingungen</Link> bleiben einsehbar.</p></div></section>
  <section><h2>2. Leistungsumfang</h2><div><p>XPORTAL strukturiert Projektbeschreibungen, gleicht nachvollziehbare Anforderungen mit freigegebenen Freelancer-Profilen ab und ermöglicht die Speicherung mehrerer Mandate und einer Auswahl. Eine zusätzliche externe Recherche wird nur auf ausdrückliche Anforderung gestartet.</p><p>Ergebnisse enthalten Profilangaben, Kompetenzbelege und offene Punkte. Ein Profilfund bestätigt weder Interesse noch aktuelle Verfügbarkeit und garantiert keine Besetzung. Auswahl, Freelancer-Honorar und Beauftragung bleiben Sache der beteiligten Parteien.</p><p>Freigegebene Dokumente und Kontaktwege dürfen innerhalb ihrer dokumentierten Berechtigung genutzt werden. Fehlt eine Freigabe, kann ein berechtigter Nutzer bewusst eine einzelne Kontaktanfrage auslösen. Der Freelancer entscheidet selbst. Ein Gespräch oder eine manuelle Freigabe durch den Betreiber ist keine Voraussetzung des neuen Standardablaufs.</p></div></section>
  <section><h2>3. Provisionsfreie neue Vorgänge</h2><div><p>Für neue Kontaktanfragen und Beauftragungen entstehen keine Vermittlungsprovision, Erfolgsgebühr oder zusätzliche Beauftragungsgebühr. Nutzer bezahlen die Software-Nutzung im gewählten Tarif. XPORTAL wird nicht Partei eines Freelancer-Vertrags.</p><p>Historische Vermittlungsverträge mit dokumentierter damaliger Zustimmung bleiben unverändert. Die alte Gebührenlogik gilt ausschließlich für solche historischen Vorgänge.</p></div></section>
  <section><h2>4. Konto, Testphase und Karte</h2><div><p>Ein Nutzer erstellt ein Konto und bestätigt seine E-Mail. Ein neues bestätigtes Konto erhält einmalig {CREDIT_PLANS.starter.grantCredits} Starter-Credits für drei Projektanalysen, ohne Karte und ohne automatische Verlängerung.</p><p>Für den optionalen {TRIAL_DAYS}-Tage-Trial wählt der Nutzer einen Monatstarif. Vor dem Stripe-Checkout sieht er Testdauer, Kontingent, anschließenden konkreten Monatspreis und automatische Verlängerung. Kartendaten werden bei Stripe verarbeitet; XPORTAL speichert keine Kartennummern oder CVC. Der Trial enthält einmalig {TRIAL_CREDITS} Credits und beginnt erst nach serverseitig verifiziertem Abschluss mit Kartenhinterlegung. Das tatsächliche Stripe-Enddatum wird im <Link href="/konto">Konto</Link> angezeigt. Ein Erfolgslink allein aktiviert keine Rechte.</p><p>Starter- und Trial-Guthaben werden je Konto nur einmal vergeben. Trial-Credits füllen sich nicht auf; ihr Verbrauch löst keine vorzeitige Abbuchung aus. Ein Kontowechsel, erneuter Checkout oder Tarifwechsel erzeugt keinen neuen Trial. Legitimes Bestandsguthaben bleibt erhalten.</p></div></section>
  <section><h2>5. Monatspreise und Abrechnung</h2><div><ul>{PUBLIC_PRICING_PLANS.filter(plan => plan.billingModel === "fixed_monthly").map(plan => <li key={plan.id}>{plan.label}: {plan.euro} € netto pro Monat, zzgl. gesetzlicher Umsatzsteuer, mit {plan.monthlyCredits.toLocaleString("de-DE")} Credits je bestätigter bezahlter Monatsperiode.</li>)}</ul><p>Nach Ablauf des Trials beginnt automatisch das gewählte monatliche Abonnement, sofern es nicht rechtzeitig gekündigt wurde. Stripe stellt die Rechnung und versucht die Zahlung. Ein Zahlungsversuch garantiert keine erfolgreiche Abbuchung. Maßgeblich ist das bei Bestellung angezeigte Angebot.</p><p>Credits messen die Nutzung. Die Kosten einer Aktion werden vor der Ausführung angezeigt. Technisch gescheiterte KI-Läufe werden nicht belastet. Ein abgeschlossener Recherche-Lauf kann auch ohne passenden Treffer Credits verbrauchen. Nicht verbrauchte Monatscredits werden nicht kumuliert, nicht ausgezahlt und sind nicht übertragbar.</p></div></section>
  <section><h2>6. Kündigung und Zugang</h2><div><p>Der Trial kann selbstständig im Kontobereich ohne Supportkontakt gekündigt werden. Bei bestätigter Kündigung vor Trial-Ende entfällt die erste kostenpflichtige Verlängerung. Zugang innerhalb des verbleibenden Trial-Kontingents besteht bis zum bestätigten Trial-Enddatum.</p><p>Nach einer bezahlten Periode ist das Abonnement zum Ende der laufenden Monatsperiode kündbar. Zahlungsmittel und Rechnungen sind über das abgesicherte Stripe-Kundenportal erreichbar. Der Kontobereich zeigt die bestätigte Kündigung mit Enddatum. Erinnerungen vor der ersten kostenpflichtigen Verlängerung richten sich nach der tatsächlich freigegebenen Stripe-Konfiguration.</p><p>Bei fehlgeschlagener oder zusätzlich zu bestätigender Zahlung gibt es keine unberechtigten neuen Monatscredits. Nach Ende der vorhandenen Berechtigung sind neue kostenpflichtige KI-Läufe gesperrt. Gespeicherte Projekte bleiben lesbar; Rechnungen und Kontoverwaltung bleiben erreichbar. Eine bestätigte Nachzahlung stellt die zutreffenden Rechte ohne doppelte Credit-Vergabe wieder her.</p></div></section>
  <section><h2>7. Verantwortliche Nutzung und Daten</h2><div><p>Nutzer dürfen Projekt- und Profildaten nur mit entsprechender Berechtigung eingeben und für die konkrete berufliche Zusammenarbeit verwenden. Unaufgeforderte Massenansprache, systematisches Auslesen privater Daten, rechtswidrige Inhalte und Umgehung technischer Grenzen sind nicht Bestandteil des Angebots.</p><p>Die <Link href="/privacy">Datenschutzhinweise</Link> beschreiben Projektentwürfe, ausdrücklich ausgelöste Kontaktfreigaben, Abrechnung und optionale Ereignismessung. Automatisch verarbeitete Angaben müssen vor einer geschäftlichen Entscheidung geprüft werden.</p></div></section>
</main><PublicFooter /></div>; }
